"use client";

import { CheckCircle2, Printer, X } from "lucide-react";
import type { PosReceiptPreview } from "@/modules/sales/pos.types";
import { formatLkr } from "@/modules/sales/pos.utils";

export function ReceiptModal({ receipt, onClose }: { receipt: PosReceiptPreview | null; onClose: () => void }) {
  if (!receipt) return null;
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm"><section aria-modal="true" className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl" role="dialog"><div className="flex justify-end"><button aria-label="Close" className="grid size-9 place-items-center rounded-full text-slate-400 hover:bg-slate-100" onClick={onClose} type="button"><X className="size-5" /></button></div><div className="text-center"><CheckCircle2 className="mx-auto size-14 text-emerald-500" /><h2 className="mt-4 text-2xl font-black text-slate-900">Receipt preview</h2><p className="mt-1 text-xs font-medium text-slate-400">{receipt.receiptNumber}</p></div><div className="mt-6 border-y border-dashed border-slate-200 py-4">{receipt.lines.map((line) => <div className="flex justify-between gap-4 py-2 text-sm" key={line.id}><span className="text-slate-600">{line.quantity} × {line.productName}<small className="block text-slate-400">{line.unitLabel}</small></span><strong className="text-slate-800">{formatLkr(line.lineTotal)}</strong></div>)}</div><div className="mt-4 grid gap-2 text-sm"><div className="flex justify-between text-slate-500"><span>Subtotal</span><span>{formatLkr(receipt.subtotal)}</span></div><div className="flex justify-between text-lg font-black text-slate-900"><span>Total</span><span>{formatLkr(receipt.total)}</span></div></div><div className="mt-5 rounded-xl bg-amber-50 p-3 text-center text-xs font-medium leading-5 text-amber-800">Receipt preview only — the final receipt will come from a future completed-sale response. No database transaction occurred.</div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-teal-200 px-4 py-3 font-bold text-teal-700" onClick={onClose} type="button"><Printer className="size-4" />Close preview</button></section></div>;
}
