import Link from "next/link";
import { Bell, HeartPulse, LogOut, Search, ShieldCheck } from "lucide-react";
import { logoutAction } from "@/modules/auth/actions";
import { SidebarNav } from "./sidebar-nav";
import { Brand } from "@/components/ui/brand";
import type { CurrentUser } from "@/modules/auth/session";

export function AppShell({ children, user }: Readonly<{ children: React.ReactNode; user: CurrentUser }>) {
  const initials = user.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const roleName = user.roleCode === "OWNER_DOCTOR" ? "Owner Doctor" : "Pharmacist";

  return <div className="min-h-screen bg-[#f4f8f8]"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col overflow-hidden bg-[linear-gradient(180deg,#064e59_0%,#006b6b_55%,#007f72_100%)] px-4 py-6 shadow-2xl shadow-teal-950/10 lg:flex"><div className="px-2"><Link href="/dashboard"><Brand inverse /></Link></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/6 px-3 py-3 text-sm text-white"><span className="flex items-center gap-2 font-semibold"><HeartPulse className="size-4 text-teal-300" />Patient-first care</span></div><div className="mt-6 flex-1 overflow-y-auto"><SidebarNav permissions={user.permissions} /></div><div className="rounded-2xl border border-white/10 bg-teal-950/20 p-4 text-teal-50"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="size-5 text-teal-300" />Secure access</div><p className="mt-2 text-xs leading-5 text-teal-100/60">Role-based permissions and server-side session validation are active.</p></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="flex h-[72px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link className="lg:hidden" href="/dashboard"><Brand compact /></Link><div className="hidden max-w-xl flex-1 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm text-slate-400 sm:flex"><Search className="size-4" /><span>Search is available in a later phase</span></div><div className="ml-auto flex items-center gap-3"><button aria-label="Notifications" className="grid size-10 place-items-center rounded-full border border-slate-200 text-slate-500" type="button"><Bell className="size-[18px]" /></button><div className="hidden sm:block text-right"><p className="text-sm font-bold text-slate-800">{user.name}</p><p className="text-xs text-slate-500">{roleName}</p></div><div className="grid size-10 place-items-center rounded-full bg-teal-100 text-sm font-bold text-teal-800">{initials}</div><form action={logoutAction}><button aria-label="Log out" className="grid size-10 place-items-center rounded-full text-slate-400 transition hover:bg-red-50 hover:text-red-600" type="submit"><LogOut className="size-[18px]" /></button></form></div></div></header><main className="mx-auto max-w-[1480px] px-4 py-6 pb-24 sm:px-6 lg:px-8 lg:py-8">{children}</main></div><SidebarNav mobile permissions={user.permissions} /></div>;
}
