import type { AuditLogReadRow } from "@/modules/audit/audit-query.service";

function displayDate(value: string) {
  return new Intl.DateTimeFormat("en-LK", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

export function AuditLogTable({ rows }: { rows: AuditLogReadRow[] }) {
  return <section className="overflow-hidden rounded-2xl border border-neutral-border bg-neutral-surface shadow-[0_8px_30px_rgba(15,51,58,.05)]"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] border-collapse text-left text-sm"><thead className="bg-neutral-bg text-xs uppercase tracking-wider text-neutral-muted"><tr>{["Date", "Actor", "Action", "Entity", "Entity ID", "IP address", "User agent"].map((heading) => <th className="border-b border-neutral-border px-5 py-4 font-bold" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((log) => <tr className="align-top hover:bg-brand-pale/30" key={log.id}><td className="whitespace-nowrap px-5 py-4 text-neutral-muted">{displayDate(log.createdAt)}</td><td className="px-5 py-4"><strong className="block text-neutral-text">{log.actorName ?? "System"}</strong>{log.actorUsername ? <span className="text-xs text-neutral-muted">{log.actorUsername}</span> : null}</td><td className="px-5 py-4 font-semibold text-brand-default">{log.action}</td><td className="px-5 py-4 text-neutral-muted">{log.entityType}</td><td className="max-w-52 truncate px-5 py-4 font-mono text-xs text-neutral-muted" title={log.entityId ?? undefined}>{log.entityId ?? "—"}</td><td className="px-5 py-4 text-neutral-muted">{log.ipAddress ?? "—"}</td><td className="max-w-72 truncate px-5 py-4 text-xs text-neutral-muted" title={log.userAgent ?? undefined}>{log.userAgent ?? "—"}</td></tr>)}{rows.length === 0 ? <tr><td className="px-5 py-16 text-center text-neutral-muted" colSpan={7}>No audit logs yet</td></tr> : null}</tbody></table></div></section>;
}
