import Link from "next/link";
import { ArrowLeft, CircleHelp } from "lucide-react";
import { troubleshooting } from "@/content/training/catalog";
import { requireAuth } from "@/modules/auth/permissions";

export default async function TrainingTroubleshootingPage() {
  await requireAuth();
  return <div className="mx-auto max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm font-bold text-brand-default" href="/training"><ArrowLeft className="size-4" />පුහුණු මාර්ගෝපදේශයට</Link><header className="mt-5 rounded-3xl border border-brand-default/20 bg-neutral-surface p-6 shadow-sm sm:p-8"><CircleHelp className="size-8 text-brand-default" /><h1 className="mt-4 text-2xl font-black tracking-tight text-neutral-text sm:text-3xl">Practical troubleshooting</h1><p className="mt-2 leading-7 text-neutral-muted">Current code එකේ validations සහ workflow boundaries අනුව check → fix → escalate කරන්න.</p></header><div className="mt-6 grid gap-4">{troubleshooting.map((item, index) => <article className="rounded-3xl border border-neutral-border bg-neutral-surface p-5 shadow-sm sm:p-6" key={item.issue}><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-brand-default text-sm font-black text-white">{index + 1}</span><div><h2 className="text-lg font-black text-neutral-text">{item.issue}</h2><dl className="mt-4 grid gap-3 text-sm leading-6"><div><dt className="font-bold text-neutral-text">Possible reason</dt><dd className="text-neutral-muted">{item.reasons}</dd></div><div><dt className="font-bold text-neutral-text">How to check</dt><dd className="text-neutral-muted">{item.check}</dd></div><div><dt className="font-bold text-neutral-text">How to fix</dt><dd className="text-neutral-muted">{item.fix}</dd></div><div className="rounded-xl bg-status-warning-bg p-3"><dt className="font-bold text-status-warning-text">Administrator</dt><dd className="text-status-warning-text">{item.admin}</dd></div></dl></div></div></article>)}</div></div>;
}
