import Link from "next/link";
import { ArrowLeft, CircleHelp } from "lucide-react";
import { troubleshooting } from "@/content/training/catalog";
import { requireAuth } from "@/modules/auth/permissions";

export default async function TrainingTroubleshootingPage() {
  await requireAuth();
  return <div className="mx-auto max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm font-bold text-teal-700" href="/training"><ArrowLeft className="size-4" />පුහුණු මාර්ගෝපදේශයට</Link><header className="mt-5 rounded-3xl border border-teal-100 bg-white p-6 shadow-sm sm:p-8"><CircleHelp className="size-8 text-teal-700" /><h1 className="mt-4 text-3xl font-black text-slate-900">Practical troubleshooting</h1><p className="mt-2 leading-7 text-slate-600">Current code එකේ validations සහ workflow boundaries අනුව check → fix → escalate කරන්න.</p></header><div className="mt-6 grid gap-4">{troubleshooting.map((item, index) => <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6" key={item.issue}><div className="flex items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-teal-700 text-sm font-black text-white">{index + 1}</span><div><h2 className="text-lg font-black text-slate-900">{item.issue}</h2><dl className="mt-4 grid gap-3 text-sm leading-6"><div><dt className="font-bold text-slate-800">Possible reason</dt><dd className="text-slate-600">{item.reasons}</dd></div><div><dt className="font-bold text-slate-800">How to check</dt><dd className="text-slate-600">{item.check}</dd></div><div><dt className="font-bold text-slate-800">How to fix</dt><dd className="text-slate-600">{item.fix}</dd></div><div className="rounded-xl bg-amber-50 p-3"><dt className="font-bold text-amber-900">Administrator</dt><dd className="text-amber-800">{item.admin}</dd></div></dl></div></div></article>)}</div></div>;
}
