type PagePlaceholderProps = {
  title: string;
  description: string;
};

export function PagePlaceholder({ title, description }: PagePlaceholderProps) {
  return <div><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-brand-pale px-3 py-1 text-xs font-bold uppercase tracking-wider text-brand-default"><Sparkles className="size-3.5" />Reserved module</span><h1 className="mt-4 text-2xl font-black tracking-tight text-neutral-text sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-neutral-muted">{description}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-xl border border-neutral-border bg-neutral-surface px-4 py-2 text-sm font-semibold text-neutral-muted shadow-sm"><LockKeyhole className="size-4 text-brand-default" />Protected route</span></div><section className="mt-7 overflow-hidden rounded-3xl border border-neutral-border bg-neutral-surface shadow-[0_14px_50px_rgba(15,51,58,.06)]"><div className="relative grid min-h-[420px] place-items-center overflow-hidden p-8 text-center"><div className="absolute inset-0 opacity-50 [background-image:radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:22px_22px] [mask-image:radial-gradient(circle_at_center,black,transparent_72%)]" /><div className="relative max-w-md"><span className="mx-auto grid size-20 place-items-center rounded-3xl bg-gradient-to-br from-teal-50 to-emerald-100 text-brand-default shadow-inner"><Layers3 className="size-9" /></span><h2 className="mt-6 text-2xl font-black text-neutral-text">Designed for a later phase</h2><p className="mt-3 leading-7 text-neutral-muted">The workspace is styled and access-controlled, but operational data and workflows remain disabled until their dedicated implementation task.</p><div className="mt-7 inline-flex items-center gap-2 rounded-full border border-status-success-bg bg-status-success-bg px-4 py-2 text-sm font-bold text-status-success-text"><span className="size-2 rounded-full bg-emerald-500" />Foundation ready</div></div></div></section></div>;
}
import { Layers3, LockKeyhole, Sparkles } from "lucide-react";
